-- ============================================================
-- Migration 034: Backfill untracked indicator seed data
-- ============================================================
-- Context: production's `indicators` table has 92 rows, but only
-- 34 of them are accounted for in this repo's migration history
-- (10 from migration 002, 24 from migration 028). The remaining
-- 58 rows were inserted directly against Supabase (SQL editor /
-- Studio) on 2026-04-20 and 2026-04-21 and were never committed
-- as a migration, so a fresh database built from this repo's
-- migrations alone would be missing them.
--
-- This migration documents that data so the migration history
-- matches what's actually running in production. Explicit ids are
-- used to match the existing production rows exactly; ON CONFLICT
-- (id) DO NOTHING makes it a no-op there and a real backfill on
-- any environment (e.g. a fresh dev database) that doesn't have
-- these rows yet.
--
-- Two batches, reconstructed from `created_at`:
--   • ids 11–25  (2026-04-20 13:27:49) — one additional headline/
--     component indicator per Target 8–22
--   • ids 101–2103 (2026-04-21 12:10:11 / 12:11:33) — 2–4 more
--     component/complementary indicators per Target 1–21
-- ============================================================

INSERT INTO public.indicators (
  id, name, definition, tier, nbsap_target_id,
  target_2030, baseline, midterm, final_target,
  current_value, progress, status,
  km_gbf, periodicity, data_source, responsible
) VALUES

-- ── Batch: 2026-04-20 13:27:49 — one indicator per Target 8–22 ──
(11, 'Households Protected from Climate Impacts (%)', 'Proportion of households protected from floods and climate impacts through NbS/EbA', 'headline', 8, '40% households protected from floods', '9% households protected', '25% (2027)', '40% (2030)', '38%', 38, 'on-track', 'GBF Target 8', 'Annual', 'Project reports, MINEMA', ARRAY['MoE','REMA','MINAGRI']),
(12, 'Benefits from Sustainable Use of Wild Species', 'Monetary and non-monetary benefits from sustainable use of wild species accruing to communities', 'headline', 9, 'RWF 5 billion from biodiversity livelihoods', '10% tourism revenue shared', '50% increase (2027)', '100% increase; RWF 5B (2030)', '41%', 41, 'on-track', 'GBF Target 9', 'Annual', 'RDB tourism revenue sharing reports', ARRAY['RDB','REMA','MINAGRI']),
(13, 'Agricultural Area under Sustainable Management (%)', 'Proportion of agricultural, forest, and aquaculture areas under productive and sustainable management', 'headline', 10, '100% priority areas under sustainable management', '30.4% forest; 4,900 t/yr aquaculture', '50% increase (2027)', '100% priority areas (2030)', '44%', 44, 'on-track', 'GBF Target 10', 'Annual', 'MINAGRI reports, RFA records', ARRAY['MINAGRI','RFA','RAB','REMA']),
(14, 'Ecosystem Services Level (RWF)', 'Levels of ecosystem services provided by restored ecosystems and landscapes', 'headline', 11, 'RWF 15 billion ecosystem service value by 2030', 'RWF 10 billion', 'RWF 12.5 billion (2027)', 'RWF 15 billion (2030)', 'RWF 11.8B', 37, 'on-track', 'GBF Target 11', 'Annual', 'WASAC water quality, REMA ecosystem assessments', ARRAY['REMA','Ministry of Health','WASAC']),
(15, 'Urban Green/Blue Space Share (%)', 'Average share of built-up city area that is green/blue space for public use', 'headline', 12, '20% of urban area as green/blue space by 2030', 'No comprehensive assessment', '15% (2027)', '20% + City Biodiversity Index (2030)', '15%', 15, 'behind', 'GBF Target 12', 'Annual', 'City of Kigali master plan, Satellite imagery', ARRAY['MININFRA','Kigali City','REMA']),
(16, 'ABS Monetary Benefits Received', 'Monetary benefits received from utilization of genetic resources shared fairly and equitably', 'headline', 13, '100% of access agreements with fair benefit-sharing', 'No baseline', '50% agreements (2027)', '100% fair and equitable sharing (2030)', '12%', 12, 'behind', 'GBF Target 13', 'Annual', 'REMA ABS records, Nagoya Protocol compliance reports', ARRAY['REMA','Ministry of Justice']),
(17, 'Policies/Plans with Biodiversity Integration', 'Number of policies, regulations, and plans incorporating biodiversity considerations across all sectors', 'component', 14, '100% of sector plans with biodiversity; 15 plans', 'Range of biodiversity laws/policies exist', '50% of sector plans (2027)', '100% sector plans; 15 plans (2030)', '9', 47, 'at-risk', 'GBF Target 14', 'Annual', 'Ministry policy documents, District plans', ARRAY['MoE','REMA','All Sector Ministries']),
(18, 'Organizations Disclosing Nature-Related Risk', 'Number of large businesses/financial institutions taking action on nature-related risk', 'headline', 15, '100% large businesses disclosing; 30 enterprises implementing', 'Guidelines established', '50% of large businesses (2027)', '100% disclosing; 30 enterprises (2030)', '17', 30, 'at-risk', 'GBF Target 15', 'Annual', 'Company sustainability reports, REMA compliance', ARRAY['REMA','Ministry of Finance','Private Sector Federation']),
(19, 'Food Waste Index (Updated)', 'Food waste index for Rwanda — lower is better', 'component', 16, '50% reduction in food waste', '164 (Kigali), 117 (Musanze)', '30% reduction (2027)', '50% reduction (2030)', '20%', 20, 'behind', 'GBF Target 16', 'Annual', 'UNEP food waste data, NISR consumption surveys', ARRAY['REMA','MINICOM','Kigali City']),
(20, 'Biosafety Regulations & GMO Authorizations', 'Number of biosafety regulations/guidelines developed and implemented', 'headline', 17, '100% target personnel trained; all regulations in place', 'Biosafety law enacted', '50% target personnel trained (2027)', 'All regulations; 2,000 stakeholders trained (2030)', '42%', 42, 'on-track', 'GBF Target 17', 'Annual', 'REMA biosafety records, Implementation reports', ARRAY['REMA','Ministry of Health','FDA']),
(21, 'Positive Incentives for Biodiversity (%)', 'Percentage of positive incentives in place to promote biodiversity conservation', 'headline', 18, '100% of harmful incentives reformed; positive incentives scaled up', 'Subsidy review study initiated', '50% harmful incentives reformed (2027)', '100% reformed; positive incentives scaled (2030)', '22%', 22, 'behind', 'GBF Target 18', 'Annual', 'MINECOFIN budget records, Subsidy review study', ARRAY['MINECOFIN','REMA','All Sector Ministries']),
(22, 'International Public Funding for Biodiversity (USD)', 'International public funding including ODA mobilized for biodiversity conservation', 'headline', 19, 'USD 500 million total from all sources by 2030', '56% of biodiversity spending from development budgets', 'USD 250 million (2027)', 'USD 500 million (2030)', '18%', 18, 'behind', 'GBF Target 19', 'Annual', 'MINECOFIN, GEF project databases, Donor reports', ARRAY['MINECOFIN','REMA','RGF']),
(23, 'Capacity-Building Programs Implemented', 'Number of capacity-building programs implemented for biodiversity conservation', 'headline', 20, '2,000 stakeholders trained; 50 knowledge products by 2030', 'No consolidated metrics', '1,200 stakeholders trained (2027)', '2,000 trained; 50 products (2030)', '35%', 35, 'on-track', 'GBF Target 20', 'Annual', 'Training records, Research institution reports', ARRAY['REMA','Ministry of Education','Research Institutions']),
(24, 'RBIS Availability & Accessibility', 'Biodiversity information system (RBIS) for data sharing and monitoring available and accessible', 'headline', 21, '100% institutions reporting; 50 policy decisions informed', 'RBIS established as accessible web platform', '85% institutions reporting (2027)', '100% reporting; 50 decisions (2030)', '48%', 48, 'on-track', 'GBF Target 21', 'Annual', 'RBIS database records, NISR data warehouse', ARRAY['REMA','NISR','Research Institutions']),
(25, 'Stakeholder Participation in Biodiversity Decisions (%)', 'Proportion of stakeholders participating in biodiversity-related decision-making processes', 'component', 22, '50% women & 30% IPLC; 80% communities engaged', 'No consolidated baseline', '35% women & 20% IPLC (2027)', '50% women & 30% IPLC; 80% communities (2030)', '10%', 10, 'behind', 'GBF Target 22', 'Annual', 'Community participation records, GMS gender reports', ARRAY['REMA','MIGEPROF','District Authorities']),

-- ── Batch: 2026-04-21 12:10:11 / 12:11:33 — component/complementary indicators, Targets 1–21 ──
(101, 'Spatial Plans Utilising KBA Information (%)', 'Percentage of spatial plans utilising Key Biodiversity Areas (KBA) information', 'component', 1, '100% of spatial plans', 'No baseline', '50%', '100%', '20%', 20, 'behind', 'GBF Target 1', 'Annual', 'RBIS, District planning offices', ARRAY['REMA','MININFRA']),
(102, 'KBAs in Spatial Planning (Number)', 'Number of Key Biodiversity Areas included in spatial planning processes', 'component', 1, 'All identified KBAs included', 'Partial', '50% KBAs', '100% KBAs', '30%', 30, 'behind', 'GBF Target 1', 'Annual', 'RBIS, RDB records', ARRAY['REMA','RDB']),
(201, 'Degraded Wetlands Restored (ha)', 'Areas of degraded wetland ecosystems with high biodiversity importance restored', 'component', 2, 'Significant wetland area restored', 'Minimal', 'Target to be set', 'Target to be set', '12%', 32, 'at-risk', 'GBF Target 2', 'Annual', 'Field surveys, REMA wetland database', ARRAY['REMA','District Authorities']),
(202, 'Degraded Natural Forest Restored (ha)', 'Areas of degraded natural forest and reserves with high biodiversity importance restored', 'component', 2, 'Target to be set annually', 'Partial data', 'Per annual plan', 'Per annual plan', '35%', 35, 'at-risk', 'GBF Target 2', 'Annual', 'RFA records, Remote sensing', ARRAY['RFA','REMA']),
(301, 'Key Biodiversity Areas Effectively Conserved (ha)', 'Area (ha) of Key Biodiversity Areas effectively conserved', 'component', 3, 'All KBAs under effective conservation', 'Partial', '50% of KBAs', '100% of KBAs', '55%', 55, 'at-risk', 'GBF Target 3', 'Annual', 'RDB, REMA KBA records', ARRAY['RDB','REMA']),
(302, 'Ramsar Wetlands Effectively Managed (ha)', 'Area (ha) of wetlands of international importance conserved and effectively managed', 'component', 3, 'All Ramsar sites under effective management', 'Partial management', 'Full management plans', 'Full management + monitoring', '60%', 60, 'at-risk', 'GBF Target 3', 'Annual', 'REMA wetland records, Ramsar reports', ARRAY['REMA','RDB']),
(401, 'HWC Management Guidelines Developed', 'Number of guidelines developed to protect genetic diversity and manage human-wildlife conflict', 'headline', 4, 'Comprehensive HWC guidelines in place', 'Minimal formal guidelines', 'Guidelines developed', 'Guidelines implemented + monitored', '30%', 30, 'behind', 'GBF Target 4', 'Annual', 'RDB, REMA policy records', ARRAY['RDB','REMA']),
(402, 'Threatened Species Improving in Status (%)', 'Percentage of threatened species that are improving in conservation status', 'component', 4, '>=50% of threatened species improving', 'Low', '20% improving', '50% improving', '18%', 18, 'behind', 'GBF Target 4', 'Biannual', 'IUCN Red List assessments, Wildlife surveys', ARRAY['RDB','REMA','ARCOS','Nature Rwanda','IUCN','RWCA','IGCP','Karisoke']),
(403, 'CITES Species Conservation Status', 'Conservation status of CITES-listed species stabilized or improved', 'component', 4, 'All CITES Appendix species stabilized/improved', 'Variable', 'Status assessed', 'Status stabilized/improved', '40%', 40, 'at-risk', 'GBF Target 4', 'Annual', 'CITES reports, RDB wildlife records', ARRAY['RDB','REMA']),
(501, 'Fish Stocks within Sustainable Levels (%)', 'Proportion of fish stocks within biologically sustainable levels', 'component', 5, '100% of fish stocks at sustainable levels', 'Declining (Lake Kivu: 16,194 t in 2020)', 'Stabilized', 'All stocks sustainable', '35%', 35, 'behind', 'GBF Target 5', 'Annual', 'RAB fisheries data, Lake Kivu monitoring', ARRAY['RAB','MINAGRI']),
(502, 'Wild Species Enforcement Inspections', 'Number of inspections to enforce regulations for wild species and fisheries', 'complementary', 5, 'Regular quarterly inspections', 'Irregular', 'Quarterly inspections nationwide', 'Systematic enforcement', '45%', 45, 'behind', 'GBF Target 5', 'Quarterly', 'RFA, RAB, RWB enforcement records', ARRAY['RFA','RAB','REMA']),
(601, 'IAS Introduction Events (Number)', 'Number of invasive alien species introduction events recorded', 'component', 6, 'Near-zero new IAS introductions', 'Multiple annual events', '50% reduction in events', 'Near-zero events', '25%', 25, 'behind', 'GBF Target 6', 'Quarterly', 'RBIS, REMA surveillance reports', ARRAY['REMA','RDB']),
(602, 'IAS on National Lists (GRIIS)', 'Number of invasive species on national lists per the Global Register of Introduced and Invasive Species', 'complementary', 6, 'Comprehensive national IAS list maintained', '47 species (2016)', 'Updated list', 'Comprehensive + management plans', '30%', 30, 'behind', 'GBF Target 6', 'Annual', 'REMA, GRIIS database', ARRAY['REMA','Research Institutions']),
(701, 'Fertilizer Efficiency (%)', 'Proportion of fertilizers used efficiently (reduced nutrient loss)', 'component', 7, 'Significant improvement in N-use efficiency', 'High NPK use; poor efficiency', '30% efficiency improvement', '50% efficiency improvement', '20%', 20, 'behind', 'GBF Target 7', 'Annual', 'MINAGRI input records, REMA monitoring', ARRAY['MINAGRI','REMA']),
(702, 'Wastewater Safely Treated (%)', 'Proportion of domestic and industrial wastewater safely treated', 'component', 7, 'Significant increase in wastewater treatment', 'Low', '50% treatment', '80%+ treatment', '30%', 30, 'at-risk', 'GBF Target 7', 'Annual', 'WASAC, RWB treatment facility records', ARRAY['WASAC','REMA']),
(703, 'Nitrogen Loss in Environment (Amount)', 'Amount of nitrogen loss in the environment from agricultural activities', 'complementary', 7, 'Significant reduction in N loss', 'High N loss from fertilizer', '30% reduction', '50% reduction', '15%', 15, 'behind', 'GBF Target 7', 'Annual', 'MINAGRI, REMA water quality data', ARRAY['MINAGRI','REMA']),
(704, 'Solid Waste Collected & Managed (%)', 'Proportion of solid waste collected and safely managed', 'complementary', 7, 'High waste collection and management rate', 'Variable across districts', '70% collection', '90%+ collection', '55%', 55, 'on-track', 'GBF Target 7', 'Annual', 'City of Kigali, District waste reports', ARRAY['REMA','MINICOM','Kigali City']),
(801, 'GHG Inventories from Land Use Change', 'National greenhouse gas inventories from land use and land use change (LULUCF)', 'component', 8, 'Annual GHG inventories completed', 'Irregular reporting', 'Annual inventories', 'Annual inventories + trend analysis', '50%', 50, 'on-track', 'GBF Target 8', 'Annual', 'REMA, National GHG inventory', ARRAY['REMA','MoE']),
(802, 'Above-Ground Biomass Stock in Forests (t/ha)', 'Above-ground biomass stock in forests (tonnes per hectare)', 'complementary', 8, 'Increasing biomass stock', 'Current forest 30.4% cover', 'Maintained or increasing', 'Significantly increased', '60%', 60, 'on-track', 'GBF Target 8', 'Annual', 'Remote sensing, RFA National Forest Inventory', ARRAY['RFA','REMA']),
(803, 'Local Govts with DRR Strategies (%)', 'Proportion of local governments with disaster risk reduction strategies aligned to national framework', 'complementary', 8, 'All districts with DRR strategies', 'Partial', '75% of districts', '100% of districts', '45%', 45, 'at-risk', 'GBF Target 8', 'Annual', 'MINEMA, District development plans', ARRAY['MINEMA','REMA','District Authorities']),
(901, 'People Benefiting from Wild Resources', 'Number of people benefiting from wild resources for food, medicinal use, craft making and culture', 'component', 9, 'Significant increase in beneficiaries', 'Limited baseline', '50% increase', '100% increase', '45%', 45, 'on-track', 'GBF Target 9', 'Annual', 'Community surveys, CBO records, RDB data', ARRAY['RDB','District Authorities']),
(902, 'Genetic Resources in Conservation Facilities', 'Number of plant and animal genetic resources for food and agriculture secured in conservation facilities', 'complementary', 9, 'Comprehensive genetic resource conservation', 'Partial', 'Significant increase', 'Comprehensive coverage', '35%', 35, 'at-risk', 'GBF Target 9', 'Annual', 'RAB genebank, Research institutions', ARRAY['RAB','Research Institutions']),
(1001, 'Forest Management Certification', 'Total forest management certification by responsible institution', 'component', 10, 'Significant certified forest area', 'Partial certification', '50% of managed forest', 'Comprehensive certification', '40%', 40, 'at-risk', 'GBF Target 10', 'Annual', 'RFA certification records', ARRAY['RFA','REMA']),
(1002, 'Small-Scale Food Producer Income (Average)', 'Average income of small-scale food producers from sustainable agriculture', 'component', 10, 'Significant income increase', 'Current average income', '20% increase', '40% increase', '50%', 50, 'on-track', 'GBF Target 10', 'Annual', 'MINAGRI, RAB surveys, District agricultural reports', ARRAY['MINAGRI','RAB','District Authorities']),
(1003, 'Degraded Agriculture & Forest Land (%)', 'Proportion of degraded agriculture and forest land', 'complementary', 10, 'Significant reduction in degraded land', 'Significant degradation', '20% reduction', '40% reduction', '35%', 35, 'at-risk', 'GBF Target 10', 'Annual', 'MINAGRI, RFA, Remote sensing', ARRAY['MINAGRI','RFA','REMA']),
(1101, 'WASH Mortality Rate', 'Mortality rate attributable to unsafe water/sanitation/hygiene services', 'component', 11, 'Significant reduction in WASH mortality', 'Current WASH mortality', '20% reduction', '40% reduction', '45%', 45, 'on-track', 'GBF Target 11', 'Annual', 'Ministry of Health facility records, WASAC', ARRAY['Ministry of Health','WASAC']),
(1102, 'PM2.5/PM10 Particulate Matter Levels', 'Annual mean levels of fine particulate matter (PM2.5 and PM10) across districts', 'component', 11, 'Below WHO guideline levels', 'High in urban/industrial areas', '20% reduction', 'Meet WHO guidelines', '30%', 30, 'at-risk', 'GBF Target 11', 'Annual', 'Meteo Rwanda air quality stations, REMA monitoring', ARRAY['REMA','Meteo Rwanda']),
(1103, 'Water Bodies with Good Ambient Quality (%)', 'Proportion of bodies of water with good ambient water quality', 'component', 11, '90% of water bodies meeting quality standards', 'Partial compliance', '70% compliance', '90% compliance', '55%', 55, 'on-track', 'GBF Target 11', 'Biannual', 'WASAC, REMA water quality reports, RBIS', ARRAY['WASAC','REMA']),
(1104, 'Annual Soil Loss by Erosion', 'Annual soil loss by erosion (tonnes per hectare per year)', 'component', 11, 'Significant reduction in soil erosion', 'High erosion in hilly terrain', '20% reduction', '40% reduction', '40%', 40, 'on-track', 'GBF Target 11', 'Annual', 'REMA erosion monitoring, Field surveys, MINAGRI', ARRAY['REMA','MINAGRI','RFA']),
(1201, 'Recreation & Cultural Services Area (ha)', 'Area providing recreation and cultural services in urban settings (hectares)', 'component', 12, 'Significant increase in recreational area', 'Limited data', 'Baseline established + increase', 'Per city NbS plans', '20%', 20, 'behind', 'GBF Target 12', 'Annual', 'City/District planning records, RBIS', ARRAY['MININFRA','Kigali City']),
(1202, 'Urban Forestry Area (ha)', 'Area under urban forestry (hectares) across cities and towns', 'component', 12, 'Significant urban forestry expansion', 'Limited data', 'Baseline + increase', 'Per city NbS plans', '18%', 18, 'behind', 'GBF Target 12', 'Annual', 'City/District urban planning, MININFRA', ARRAY['MININFRA','RFA','Kigali City']),
(1203, 'City Biodiversity Index (Kigali & Secondary Cities)', 'City Biodiversity Index (CBI) for Kigali, satellite and secondary cities', 'complementary', 12, 'CBI established and improving for all major cities', 'Not yet established', 'CBI baseline established', 'CBI operational for all cities', '5%', 5, 'behind', 'GBF Target 12', 'Annual', 'Satellite imagery, Biodiversity surveys, City records', ARRAY['MININFRA','REMA','Kigali City']),
(1301, 'ABS Non-Monetary Benefits Received', 'Non-monetary benefits received (technology transfer, capacity building, joint research) from genetic resource utilization', 'headline', 13, 'Non-monetary benefits systematically tracked and shared', 'No baseline', 'Framework established', 'Systematic tracking + sharing', '10%', 10, 'behind', 'GBF Target 13', 'Annual', 'REMA ABS records, Research institution records', ARRAY['REMA','Research Institutions']),
(1302, 'ABS Regulations Developed', 'Number of regulations developed to ensure fair and equitable sharing of benefits from genetic resources', 'component', 13, 'Comprehensive ABS legal framework', 'Nagoya Protocol framework', 'Additional regulations', 'Full implementation', '25%', 25, 'behind', 'GBF Target 13', 'Annual', 'REMA, Ministry of Justice policy records', ARRAY['REMA','Ministry of Justice']),
(1303, 'Genetic Resource Authorizations Granted', 'Number of authorizations granted for access to genetic resources including traditional knowledge', 'component', 13, 'Systematic authorization process', 'Ad hoc', 'Formal system established', 'All access authorized', '15%', 15, 'behind', 'GBF Target 13', 'Annual', 'REMA ABS clearing-house', ARRAY['REMA']),
(1304, 'ABS Certificates in Clearing-House', 'Number of internationally recognized certificates of compliance in ABS Clearing-House', 'complementary', 13, 'Rwanda registered in international ABS system', 'None', 'First certificates', 'Active participation', '5%', 5, 'behind', 'GBF Target 13', 'Annual', 'REMA, CBD ABS Clearing-House', ARRAY['REMA']),
(1401, 'Cross-Sectoral Biodiversity Collaborations', 'Increase in cross-sectoral collaborations and joint initiatives for biodiversity', 'complementary', 14, 'All major sectors in formal collaboration', 'Limited', '5 cross-sectoral initiatives', '10+ cross-sectoral initiatives', '45%', 40, 'at-risk', 'GBF Target 14', 'Annual', 'REMA mainstreaming reports, Ministry records', ARRAY['REMA','All Sector Ministries']),
(1402, 'Public Awareness & Participation Enhancement', 'Enhancement in public awareness and participation in biodiversity conservation', 'complementary', 14, 'Measurable increase in public awareness', 'Limited baseline', 'Baseline established + improvement', 'Significant awareness increase', '40%', 35, 'behind', 'GBF Target 14', 'Annual', 'Surveys, Media monitoring, Engagement records', ARRAY['REMA','District Authorities','NGOs']),
(1501, 'Action Plans on Nature-Related Risk', 'Number of action plans designed following reports on nature-related risk and biodiversity impacts', 'component', 15, 'All large businesses with action plans', 'None', '25% with action plans', '100% with action plans', '15%', 15, 'behind', 'GBF Target 15', 'Annual', 'Company sustainability reports, REMA compliance records', ARRAY['REMA','Private Sector']),
(1502, 'Companies Publishing Sustainability Reports', 'Number of companies in Rwanda publishing sustainability reports with biodiversity information', 'complementary', 15, 'All large companies publishing sustainability reports', 'Few companies', '50% of large companies', '100% of large companies', '20%', 20, 'behind', 'GBF Target 15', 'Annual', 'Company reports, PSF records', ARRAY['REMA','Private Sector Federation']),
(1601, 'Material Footprint per Capita', 'Material footprint per capita (tonnes of material extracted to meet consumption demands)', 'component', 16, 'Reduction in material footprint', 'Not yet established', 'Baseline established', 'Measurable reduction', '10%', 10, 'behind', 'GBF Target 16', 'Annual', 'NISR consumption surveys, REMA waste reports', ARRAY['NISR','REMA']),
(1602, 'Ecological Footprint per Capita', 'Ecological footprint per capita (global hectares) — lower is better', 'component', 16, 'Maintained at low level (0.55 gha/capita)', '0.55 gha/capita (Global Footprint Network 2022)', 'Maintained <=0.55', 'Maintained or reduced', '55%', 55, 'on-track', 'GBF Target 16', 'Annual', 'Global Footprint Network, NISR data', ARRAY['REMA','NISR']),
(1603, 'Recycling Rate (%)', 'Proportion of waste recycled or reused across all sectors', 'complementary', 16, 'Significant increase in recycling rate', 'Low', 'Measurable increase', 'High recycling rate', '25%', 25, 'behind', 'GBF Target 16', 'Annual', 'REMA waste management reports, City records', ARRAY['REMA','MINICOM']),
(1701, 'Biosafety Personnel Trained', 'Number of people (public and private sector) trained on biosafety measures and GMO management', 'component', 17, '2,000 stakeholders trained by 2030', 'Limited', '1,000 trained (2027)', '2,000 trained (2030)', '40%', 40, 'on-track', 'GBF Target 17', 'Annual', 'Training institution records, REMA', ARRAY['REMA','Ministry of Health','Research Institutions']),
(1702, 'Accredited Biosafety Laboratories', 'Number of laboratories and facilities accredited for biosafety research and testing', 'component', 17, 'Sufficient accredited facilities nationwide', 'Limited', 'Baseline + increase', 'Comprehensive coverage', '30%', 30, 'at-risk', 'GBF Target 17', 'Annual', 'Laboratory accreditation documents, RBS records', ARRAY['REMA','RSB','Research Institutions']),
(1703, 'Biosafety Risk Assessment Reports', 'Frequency of monitoring and scientific reports on risk assessment for biosafety-related projects', 'complementary', 17, 'Regular risk assessment reports', 'Irregular', 'Annual systematic reports', 'Quarterly monitoring', '35%', 35, 'at-risk', 'GBF Target 17', 'Annual', 'REMA biosafety reports', ARRAY['REMA','Research Institutions']),
(1801, 'Harmful Subsidies Eliminated or Reformed (Value)', 'Value of subsidies harmful to biodiversity that have been eliminated, phased out or reformed', 'headline', 18, 'All identified harmful subsidies reformed', 'Study in progress', '50% reformed', '100% reformed', '15%', 15, 'behind', 'GBF Target 18', 'Annual', 'MINECOFIN, Subsidy review results', ARRAY['MINECOFIN','REMA']),
(1802, 'Environmentally Harmful Agricultural Support Trend', 'Trends in potentially environmentally harmful elements from government support to agriculture', 'complementary', 18, 'Declining trend in harmful agricultural support', 'Study in progress', 'Declining trend', 'Eliminated harmful support', '20%', 20, 'behind', 'GBF Target 18', 'Annual', 'MINECOFIN, MINAGRI budget, REMA', ARRAY['MINECOFIN','MINAGRI']),
(1901, 'Domestic Public Funding for Biodiversity (RWF)', 'Domestic public funding allocated for biodiversity conservation and sustainable use', 'headline', 19, 'RWF 10 billion domestic biodiversity funding', 'RWF 6 billion current', 'RWF 8 billion (2027)', 'RWF 10 billion (2030)', '53%', 53, 'on-track', 'GBF Target 19', 'Annual', 'MINECOFIN budget reports, FONERWA records', ARRAY['MINECOFIN','REMA']),
(1902, 'Private Biodiversity Finance (USD)', 'Private funding (domestic and international) mobilized for biodiversity conservation', 'headline', 19, 'Significant private finance component of USD 500M target', 'Minimal', 'Growing private investment', 'Substantial private finance', '22%', 22, 'behind', 'GBF Target 19', 'Annual', 'Private sector reports, NGO records, FONERWA', ARRAY['RGF','REMA','Private Sector']),
(1903, 'GEF & International Facility Funding', 'Amount of funding mobilized through the Global Environment Facility (GEF) and other international facilities', 'complementary', 19, 'Maximize GEF and international funding for Rwanda', 'Existing GEF projects', 'Increased portfolio', 'Comprehensive GEF engagement', '45%', 45, 'on-track', 'GBF Target 19', 'Annual', 'GEF project databases, REMA records', ARRAY['REMA','MINECOFIN']),
(2001, 'Biodiversity Technology Adoption', 'Adoption of new biodiversity monitoring and conservation technologies', 'headline', 20, 'Widespread technology adoption for biodiversity monitoring', 'Limited adoption', 'Significant adoption', 'Comprehensive adoption', '30%', 30, 'at-risk', 'GBF Target 20', 'Annual', 'RBIS, REMA capacity reports', ARRAY['REMA','Research Institutions']),
(2002, 'Stakeholders Trained in Biodiversity M&E', 'Number of participants trained in biodiversity monitoring and conservation techniques', 'component', 20, '2,000 individuals trained', '500', '1,200', '2,000', '1,050', 55, 'on-track', 'GBF Target 20', 'Annual', 'Training records, Workshop attendance logs', ARRAY['REMA','Sector Ministries','NGOs']),
(2003, 'Collaborative Research Projects & Publications', 'Number of collaborative research projects and scientific publications on biodiversity', 'component', 20, 'Significant research output', 'Limited', 'Baseline + increase', 'Robust research portfolio', '40%', 40, 'on-track', 'GBF Target 20', 'Annual', 'Research institution reports, Publication databases', ARRAY['Research Institutions','REMA','Universities']),
(2101, 'Biodiversity Knowledge Products (Number)', 'Reports, maps, policy briefs, and other biodiversity knowledge products generated', 'component', 21, '50 knowledge products by 2030', '20', '35', '50', '31', 55, 'on-track', 'GBF Target 21', 'Annual', 'REMA publications, RBIS, CHM Rwanda', ARRAY['REMA','Research Institutions']),
(2102, 'Timely CBD Report Submissions (%)', 'Reports submitted as per CBD national reporting requirements and timeline', 'binary', 21, '100% compliance with CBD reporting', '70%', '85%', '100%', '80%', 67, 'on-track', 'GBF Target 21', 'Annual', 'REMA reports, CBD ORT records', ARRAY['REMA','Sector Ministries']),
(2103, 'Education for Sustainable Development Mainstreaming', 'Extent to which global citizenship education and education for sustainable development are mainstreamed in national education policies', 'component', 21, 'Full mainstreaming in education system', 'Partial', '50% mainstreamed', 'Fully mainstreamed', '35%', 35, 'at-risk', 'GBF Target 21', 'Annual', 'Ministry of Education, REB records', ARRAY['Ministry of Education','REMA'])

ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  RAISE NOTICE 'Migration 034 complete: 72 previously-untracked indicator rows backfilled (ids 11-25, 101-2103).';
  RAISE NOTICE 'indicators table migration history now matches production (10 + 72 + 10 = 92 rows).';
END $$;
